Docs
askbuddie/bikram-sambat pull request #39
Opened 2023-08-28 16:08 UTC by thebishalniroula

### Description
Docs for Bikram Sambat Library using nextra

2023-08-28 16:20 UTC, ashiishme commented on docs/LICENSE
Can you remove this file, we don't need it inside docs.

2023-08-28 16:20 UTC, ashiishme commented on docs/README.md
Same as above.

2023-08-28 16:20 UTC, ashiishme commented on docs/next.config.js
> +  themeConfig: './theme.config.tsx',
Make sure the theme color reflects Ask Buddie brand color in light mode.

2023-08-28 16:21 UTC, ashiishme commented on docs/package.json
> +  "description": "Docs for @askbuddie/bikram-sambat",
```suggestion
  "description": "Documentation for Bikram Sambat date picker by Ask Buddie",
```

2023-08-28 16:23 UTC, ashiishme commented on docs/theme.config.tsx
> +  logo: <span>Bikram sambat</span>,
```suggestion
  logo: <span>Bikram Sambat</span>,
```

2023-08-28 16:23 UTC, ashiishme commented on docs/theme.config.tsx
> +    link: "https://discord.com/channels/735870405709135924",
```suggestion
    link: "https://dsc.gg/askbuddie",
```

2023-08-28 16:24 UTC, ashiishme commented on docs/theme.config.tsx
> +  docsRepositoryBase: "https://github.com/askbuddie/bikram-sambat-docs",
```suggestion
  docsRepositoryBase: "https://github.com/askbuddie/bikram-sambat",
```

2023-08-28 16:24 UTC, ashiishme commented on docs/theme.config.tsx
> +    text: "Bikram Sambat by Askbuddie",
```suggestion
    text: "Bikram Sambat by Ask Buddie",
```

2023-08-28 16:25 UTC, ashiishme commented on src/BikramSambat.test.ts
Revert this file, seems like the changes are coming from the your prettier config.

2023-08-28 16:25 UTC, ashiishme commented on src/BikramSambat.ts
Same as above, revert this file.

2023-08-28 16:30 UTC, asujan205 commented on docs/next.config.js
> +  themeConfig: './theme.config.tsx',
change primaryHue value in theme.config,tsx

2023-08-28 17:05 UTC, thebishalniroula commented
@ashiishme dai, should have been fixed.

2023-08-28 17:15 UTC, blackkspydo requested changes

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/comparing-dates/is-after.mdx
> +Returns `true` if the current date is after the provided Bikram Sambat date.
```suggestion
Returns `true` if the provided Bikram Sambat date is after the current date.
```

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/comparing-dates/is-after.mdx
> +const date2 = new BikramSambat("2078-04-15");
```suggestion
const date2 = new BikramSambat("2078-06-15");
```

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/comparing-dates/is-before.mdx
> +Returns `true` if the current date is before the provided Bikram Sambat date.
```suggestion
Returns `true` if the provided Bikram Sambat date is before tha current date.
```

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/comparing-dates/is-before.mdx
> +const date2 = new BikramSambat("2078-06-15");
```suggestion
const date2 = new BikramSambat("2078-04-15");
```

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/formating-dates/format.mdx
> +
can you add this block please

The supported date formats are:

```jsx
- YYYY  // 2080
- YYYY-MM // 2080-12
- YYYY-MM-DD  // 2080-12-31
- YYY-MM-DD // 080-12-31
- YY-MM-DD  // 80-12-31
- DD-MMMM-YYYY  // 31-Chaitra-2080
- DD-MM-YYYY  // 31-12-2080
- MMMM-DD-YYYY  // Chaitra-31-2080
- MMMM DD,YYYY  // Chaitra 31,2080
```
<!-- '-' | '/' | ' ' | '. ' -->
Note: The date format can be separated by any of the following characters: `-`, `/`, `(space)`, `(dot)`.

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/navigating-dates/get-previous-year.mdx
why is this file empty

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/navigating-dates/is-leap-year.mdx
> +const isLeap = date.isLeapYear(); // false (Example value)
```suggestion
const date = new BikramSambat("2078-05-15");
const isLeap = date.isLeapYear(); // false (Example value)
```

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/properties/day.mdx
let's remove this file, properties are internal use only

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/properties/month.mdx
let's remove this file, properties are internal use only

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/properties/year.mdx
let's remove this file, properties are internal use only

2023-08-28 17:15 UTC, blackkspydo commented on docs/pages/table-of-contents.mdx
> +  - [day](properties/day)
lets remove this too

2023-08-29 01:09 UTC, blackkspydo approved these changes

2023-08-29 01:15 UTC, merged